links = [ 
    { cat="2025", date="2025-05-20", title="How to build your resume with an SSG", arc="20250520160612", url= "https://ktema.org/articles/the-overengineered-resume/" },
    { cat="2025", date="2025-05-28", title="Ship Software That Does Nothing", url= "https://kerrick.blog/articles/2025/ship-software-that-does-nothing/" },
    { cat="2025", date="2025-05-28", title="Basic Hacks for Kobo E-Readers", url= "https://www.linux-magazine.com/Online/Features/Basic-Hacks-for-Kobo-E-Readers" },
    { cat="2025", date="2025-05-28", title="Windows NT vs. Unix - A design comparison", url= "https://blogsystem5.substack.com/p/windows-nt-vs-unix-design" },
    { cat="2025", date="2025-05-29", title="Build Your Own Text Editor", url= "https://viewsourcecode.org/snaptoken/kilo/index.html" },
    { cat="2025", date="2025-06-09", title="The Intelligence Curse", url= "https://intelligence-curse.ai/" },
    { cat="2025", date="2025-06-20", title="Writing Toy Software Is A Joy", url= "https://blog.jsbarretto.com/post/software-is-joy" },
    { cat="2025", date="2025-07-15", title="Let me pay for Firefox", url= "https://discourse.mozilla.org/t/let-me-pay-for-firefox/141297" },
    { cat="2025", date="2025-07-23", title="Flash of unstyled content (FOUC) ", url="https://en.wikipedia.org/wiki/Flash_of_unstyled_content" },
    { cat="2025", date="2025-11-24", title="A History of Laptop Displays", url="https://www.dosdays.co.uk/topics/laptop_displays.php" },
    { cat="2025", date="2025-12-12", title="The Copenhagen Trap", arc="20251212191744", url="https://aliveness.kunnas.com/articles/copenhagen-trap" },
# { date="", title="", url="" },
]